version: '3'

services:
  postgres:
    image: postgres
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: admin_projeto
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: multitenancy_project
