# Generated by Django 5.0.2 on 2024-02-11 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='domain_url',
        ),
    ]
