# Generated by Django 5.0.2 on 2024-02-11 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mydomain'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyDomain',
            new_name='Domain',
        ),
    ]
